# $Header: /home/cjm/cvs/libdprt-jni_general/Makefile.common,v 1.1 2025-02-05 09:44:59 cjm Exp $

JNI_HOME		= jni_general
LIBDPRT_JNI_SRC_HOME	= $(LIBDPRT_SRC_HOME)/$(JNI_HOME)
LIBDPRT_JNI_BIN_HOME	= $(LIBDPRT_BIN_HOME)/$(JNI_HOME)
LIBDPRT_JNI_DOC_HOME	= $(LIBDPRT_DOC_HOME)/$(JNI_HOME)

#
# $Log: not supported by cvs2svn $
#
